import {
  LayoutTemplate,
  Search,
  MapPin,
  ShieldCheck,
  PanelTop,
  Gauge,
  Flame,
  Droplet,
  Home,
  SearchCheck,
  Code2,
  FileText,
  BarChart3,
  Smartphone,
  MousePointerClick,
  Phone,
  ListChecks,
  ServerCog,
  Accessibility,
  Sparkles,
  Building2,
  PawPrint,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  layout: LayoutTemplate,
  search: Search,
  "map-pin": MapPin,
  "shield-check": ShieldCheck,
  "panel-top": PanelTop,
  gauge: Gauge,
  flame: Flame,
  droplet: Droplet,
  home: Home,
  "search-check": SearchCheck,
  code: Code2,
  "file-text": FileText,
  "bar-chart": BarChart3,
  smartphone: Smartphone,
  "mouse-pointer-click": MousePointerClick,
  phone: Phone,
  "list-checks": ListChecks,
  "server-cog": ServerCog,
  accessibility: Accessibility,
  sparkles: Sparkles,
  building: Building2,
  "paw-print": PawPrint,
};
